# Generated by Django 3.0.3 on 2020-04-11 22:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(blank=True, help_text='This should be the email you would like to recieve notifcations to.', max_length=100, null=True)),
                ('email_password', models.CharField(blank=True, max_length=100, null=True)),
                ('recieve_notifications', models.BooleanField(default=True, help_text='Turn this on to get emails notifying you when someone has contacted you.')),
                ('on_holiday', models.BooleanField(default=False, help_text='Set this to True if you will not be replying for a while.')),
                ('contact_message', models.TextField(help_text='This is the message that shows on the contact page before they get in touch.')),
                ('thanks_message', models.TextField(help_text='This is the message that shows when they succesfully send you a message.')),
                ('holiday_message', models.TextField(help_text='This is the message that shows to notify you will not be replying for a while.')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The front facing name of the topic.', max_length=200)),
                ('slug', models.CharField(help_text='This is how the topic is stored in the db.', max_length=200)),
                ('active', models.BooleanField(default=True, help_text='Toggle visibility to the users.')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(help_text='Note down any actions you want to take or notes.')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Topic')),
            ],
        ),
    ]
