# Generated by Django 3.0.3 on 2020-04-12 14:17

from django.db import migrations, models


def create_default_contact_settings(apps, schema_editor):
    ContactSettings = apps.get_model('home', 'ContactSettings')
    ContactSettings.objects.create(
        on_holiday=False,
        contact_message='I\'ll try to reply back ASAP. You can expect an answer soon.',
        thanks_message='Thanks for getting in touch.',
        holiday_message='Unfortunately, I may be slow to reply because I\'m currently away.'
    )


def rollback(apps, schema_editor):
    ContactSettings = apps.get_model('home', 'ContactSettings')
    ContactSettings.objects.get().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(blank=True, help_text='This should be the email you would like to recieve notifcations to.', max_length=100, null=True)),
                ('email_password', models.CharField(blank=True, max_length=100, null=True)),
                ('on_holiday', models.BooleanField(default=False, help_text='Set this to True if you will not be replying for a while.')),
                ('contact_message', models.TextField(help_text='This is the message that shows on the contact page before they get in touch.')),
                ('thanks_message', models.TextField(help_text='This is the message that shows when they succesfully send you a message.')),
                ('holiday_message', models.TextField(help_text='This is the message that shows to notify you will not be replying for a while.')),
            ],
        ),
        migrations.RunPython(create_default_contact_settings, rollback)
    ]
