# Generated by Django 3.0.3 on 2020-04-12 22:38

from django.db import migrations, models


def create_about_settings(apps, schema_editor):
    AboutSettings = apps.get_model('home', 'AboutSettings')
    AboutSettings.objects.create()


def rollback(apps, schema_editor):
    AboutSettings = apps.get_model('home', 'AboutSettings')
    AboutSettings.objects.get().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200412_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.TextField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('email_address', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RunPython(create_about_settings, rollback)
    ]
