# Generated by Django 3.0.3 on 2020-04-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsettings',
            name='page_title',
            field=models.CharField(default='Profile', max_length=40),
        ),
    ]
